name: projekty
description: Flutter app for calculating time to go to sleep and wake up

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  clock: ^1.1.0
  intl: ^0.17.0


dev_dependencies:
  bloc_test: ^8.3.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true